### ISSUE TITLE
Compilation error in wasm builds

### ISSUE THREAD

**Issue by zupzup** [async-graphql/async-graphql#1787]
Hey,

It seems the change in https://github.com/async-graphql/async-graphql/pull/1780, especially adding `async-io` as a dependency broke the wasm build in 7.2.0.

I stumbled on this trying to build surrealdb for wasm32-unknown-unknown (https://github.com/surrealdb/surrealdb/issues/6775), but can also reproduce it here in the repo.

The problem is that the `errno` crate gets pulled in for wasm builds, but can't compile there.

```
cargo tree -i errno --target wasm32-unknown-unknown

errno v0.3.14
└── rustix v1.1.3
    └── async-io v2.6.0
        └── async-graphql v7.2.0 (/home/mario/dev/oss/rust/async-graphql)

```

## Expected Behavior

The build for wasm32-unknown-unknown works.

## Actual Behavior

The build for wasm32-unknown-unknown fails 

## Steps to Reproduce the Problem

1. cargo build --target wasm32-unknown-unknown

The build fails with

```bash
error: The target OS is "unknown" or "none", so it's unsupported by the errno crate.
 --> /home/mario/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/errno-0.3.14/src/sys.rs:8:1
  |
8 | compile_error!("The target OS is \"unknown\" or \"none\", so it's unsupported by the errno crate.");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `errno` (lib) due to 1 previous error
```

## Specifications

- Version: 7.2.0
- Platform: wasm32

**Comment by aumetra** [comment]
Thanks for the report. Interesting that this crate is used in wasm32-unknown-unknown. Are you running it in the browser. Sounds like an interesting platform.

Anyway, sure, I will see how we fix this. Probably a conditional dependency on gloo_timers

**Comment by aumetra** [comment]
To be clear: I will fix this for 7.x but future breaking releases will remove this patch. This library is a server library, supporting the browser is explicitly out of scope. Unless they can give me an explicit good reason why browser support should be in-scope for a library that advertises itself as a, quote:

> a high-performance graphql **server** library that's fully specification compliant

**Comment by zupzup** [comment]
Awesome, thank you!

Yeah, we build our core logic in Rust and use SurrealDB for persistence. In the browser it uses IndexedDB for storage and on the server it uses RocksDB with the same code, it's quite nice.

I'm not sure why this crate is included in the SurrealDB wasm build, to be honest and I fully understand and agree that this is not really in scope for this crate. 👍 

I also created an issue on the SurrealDB issue tracker and will mention this there (https://github.com/surrealdb/surrealdb/issues/6775).

**Comment by aumetra** [comment]
Okay, new release should come through in a few minutes. Timers are stubbed out and just panic when used because I'm pretty confident nobody actually gets to a point where a timer is actually used.

So yeah.

**Comment by ipetkov** [comment]
> This library is a server library, supporting the browser is explicitly out of scope

I did want to mention that having the ability to compile to wasm is extremely valuable. We have an application which acts as a GraphQL server which we also compile to wasm and run it in the browser (which it still behaves as a GraphQL server, where the JS frontend acts as the client). The notion of what is "server" vs what is "client" is a bit arbitrary given your perspective 😄 

Anyway this is not meant to be a demand; if you, as the maintainer, choose to not want to maintain support for wasm builds that's within your rights. But we'll probably stick with our own fork if that becomes the case

**Comment by aumetra** [comment]
Hmm interesting. Well, the main issue is with stuff like WebSocket streaming, DataLoader, and multipart handling. I'll see what I can do and how much maintenance overhead it actually becomes.

This architecture sounds a little cursed but possibly "alright"?

**Comment by aumetra** [comment]
At least I should add a Wasm test to CI if the maintenance continues

**Comment by aumetra** [comment]
Okay, after @ipetkov's comment that made a pretty good point to have a server in the browser: v8 will support wasm32-unknown-unknown but will assume it's a browser.

The timer will fall back onto `gloo_timers`. Hope 1Password doesn't have to fall back to a fork, and SurrealDB won't have to change their build approach.

**Comment by ipetkov** [comment]
I was about to comment that I think its totally reasonable if specific features aren't supported on wasm: e.g. websockets and multipart support are really protocol implementations which don't make sense on wasm since wasm can't open sockets of any kind (we similarly solved this in our wasm build by using our own ffi messaging system and spawning requests without needing a protocol implementation crate)

I haven't used the dataloader, I was assuming it probably needs timers given it was brought up earlier. I was going to suggest that there could be a way to provide your own timer implementation, but for now assuming `gloo_timers` (i.e. browser) is probably much easier to do for now and evolve it if/when necessary!

**Comment by aumetra** [comment]
Yeah, I've thought about either: 
1. Making it possible to supply your own timer "factory" which we use to create delays
2. Have a crate that is a front which you can use to easily swap in own timer impls (similar to tracing's subscriber installation)
