### ISSUE TITLE
actix-web-v4-beta doesn't compile with error: no HttpResponseBuilder in dev

### ISSUE THREAD

**Issue by boardmaster357** [async-graphql/async-graphql#489]
## Expected Behavior
actix-web integration shoiuld compile.

## Actual Behavior
   Compiling actix-web-actors v4.0.0-beta.4
error[E0432]: unresolved import `actix_web::dev::HttpResponseBuilder`
  --> /home/robert/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-actors-4.0.0-beta.4/src/ws.rs:25:5
   |
25 | use actix_web::dev::HttpResponseBuilder;
   |     ^^^^^^^^^^^^^^^^-------------------
   |     |               |
   |     |               help: a similar name exists in the module: `BaseHttpResponseBuilder`
   |     no `HttpResponseBuilder` in `dev`

## Steps to Reproduce the Problem

1. Checkout branch actix-web-v4-beta
2. cd integrations/actix-web 
3. cargo build

## Specifications

- Version: actix-web-v4-beta
- Platform: Linux Mint 20.1
- Subsystem: integrations/actix-web

**Comment by kennetpostigo** [comment]
Hi @sunli829 ,

I'm converting my project from async-std/tide -> tokio/actix-web and the actix members are recommending using the 4.0 beta because of my actix/tokio/sqlx usage. Do you know of any workarounds for being able to use actix 4.0 beta?

At the moment the only issue I actually have is for this piece of code:
```rust
use actix_web::{get, post, web, HttpResponse};
use async_graphql::http::{playground_source, GraphQLPlaygroundConfig};
use async_graphql::{EmptySubscription, Schema};
use async_graphql_actix_web::{Request, Response};
use sqlx::{Pool, Postgres};

#[post("/graphql")]
async fn graphql(
  schema: web::Data<Schema<Query, Mutation, EmptySubscription>>,
  req: Request,
) -> Response {
  schema.execute(req.into_inner()).await.into()
}
```

Produces this error:
```rust
error[E0277]: the trait bound `fn(actix_web::web::Data<async_graphql::Schema<gql::types::Query, gql::types::Mutation, async_graphql::EmptySubscription>>, async_graphql_actix_web::Request) -> impl std::future::Future {<gql::graphql as actix_web::dev::HttpServiceFactory>::register::graphql}: actix_web::dev::Handler<_, _>` is not satisfied
  --> platform/errors/src/gql/mod.rs:11:10
   |
11 | async fn graphql(
   |          ^^^^^^^ the trait `actix_web::dev::Handler<_, _>` is not implemented for `fn(actix_web::web::Data<async_graphql::Schema<gql::types::Query, gql::types::Mutation, async_graphql::EmptySubscription>>, async_graphql_actix_web::Request) -> impl std::future::Future {<gql::graphql as actix_web::dev::HttpServiceFactory>::register::graphql}`
```

**Comment by zengxs** [comment]
This works with `actix-web@4.0.0-beta.6`:
```rust
use async_graphql::*;
use actix_web::{post, web, HttpResponse, Responder};

struct RequestWrapper(Request);

#[post("/graphql")]
async fn web_graphql(
    schema: web::Data<ActixSchema>,
    body: web::Bytes,
) -> actix_web::Result<impl Responder> {
    let body = std::str::from_utf8(body.as_ref())?;
    let req = serde_json::from_str::<Request>(body).unwrap();
    let req = RequestWrapper { 0: req };
    let resp = schema.execute(req).await;

    Ok(HttpResponse::Ok()
        .content_type("application/json;charset=utf-8")
        .body(serde_json::to_string(&resp).unwrap()))
}

impl Into<async_graphql::Request> for RequestWrapper {
    fn into(self) -> async_graphql::Request {
        self.0
    }
}
```

**Comment by lionkeng** [comment]
Hello, anyone with a workaround for the original problem reported in this issue by @boardmaster357 ? I am seeing the same problem by just adding async-graphql into my cargo dependencies and no additional graphQL related code in Rust.

My dependencies in my `cargo.toml` looks like this.
```
[dependencies]
actix-web = {version="4.0.0-beta.6"}
async-graphql = { git="https://github.com/async-graphql/async-graphql.git", branch="actix-web-v4-beta" }
async-graphql-actix-web = { git="https://github.com/async-graphql/async-graphql.git", branch="actix-web-v4-beta" }
```

**Comment by oeed** [comment]
For anyone using the fix by zengxs, note that it doesn't set headers, if you need those set you'll need to do manually as discovered in #566.
